apiVersion: v2
name: juice-controller
version: 1.0.10
type: application
home: https://github.com/Xdevlab/Run
icon: https://raw.githubusercontent.com/Xdevlab/Run/master/assets/Logo.svg
maintainers:
  - name: Juice Technologies, Inc.
    url: juicelabs.co
